schemaVersion: 1
enabledWorkflows: ["simulator", "ui-automation", "debugging", "logging"]
sessionDefaults:
  projectPath: ./MCPTest.xcodeproj
  scheme: MCPTest
  simulatorId: B38FE93D-578B-454B-BE9A-C6FA0CE5F096
  useLatestOS: true
  platform: iOS Simulator
  bundleId: io.sentry.MCPTest
