id: scaffold_ios_project
module: mcp/tools/project-scaffolding/scaffold_ios_project
names:
  mcp: scaffold_ios_project
  cli: scaffold-ios
description: Scaffold iOS project.
predicates:
  - hideWhenXcodeAgentMode
annotations:
  title: Scaffold iOS Project
  destructiveHint: true
nextSteps:
  - label: "Important: Before working on the project make sure to read the README.md file in the workspace root directory."
  - label: Build for simulator
    toolId: build_sim
    priority: 1
  - label: Build and run on simulator
    toolId: build_run_sim
    priority: 2
