id: swift-package
title: Swift Package Development
description: Build, test, run and manage Swift Package Manager projects.
tools:
  - swift_package_build
  - swift_package_test
  - swift_package_clean
  - swift_package_run
  - swift_package_stop
  - swift_package_list
